package main

import (
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"github.com/hiromaily/connect-example/pkg/apis"
	"github.com/hiromaily/connect-example/pkg/gen/eliza/v1/elizav1connect" // generated by protoc-gen-connect-go
	"github.com/hiromaily/connect-example/pkg/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

// Refer to
// https://github.com/bufbuild/connect-demo/blob/3a30d4de07d6ac42110acd4ebf64bb4bf8a62579/main.go

func main() {
	mux := http.NewServeMux()
	createHandlers(mux)

	// serve
	http.ListenAndServe(
		"localhost:8080",
		// h2c protocol is the non-TLS version of HTTP/2
		h2c.NewHandler(mux, &http2.Server{}),
	)
}

func createHandlers(mux *http.ServeMux) {
	// params: path, handler
	mux.Handle(greetv1connect.NewGreetServiceHandler(&apis.GreetServer{}))
	mux.Handle(elizav1connect.NewElizaServiceHandler(&apis.ElizaServer{}))
}
